collision_monitor:
  ros__parameters:
    base_frame_id: base_link
    odom_frame_id: odom
    cmd_vel_in_topic: cmd_vel_nav
    cmd_vel_out_topic: cmd_vel
    state_topic: collision_monitor_state
    transform_tolerance: 0.2
    source_timeout: 1.0
    base_shift_correction: true
    stop_pub_timeout: 1.0
    polygons: [FootprintStop, FrontSlowdown]
    FootprintStop:
      type: polygon
      action_type: stop
      footprint_topic: local_costmap/published_footprint
      time_before_collision: 1.0
      simulation_time_step: 0.1
      min_points: 3
      visualize: true
      polygon_pub_topic: footprint_stop
    FrontSlowdown:
      type: polygon
      points: "[[-0.30, -0.35], [0.65, -0.35], [0.65, 0.35], [-0.30, 0.35]]"
      action_type: slowdown
      slowdown_ratio: 0.35
      min_points: 3
      visualize: true
      polygon_pub_topic: front_slowdown
    observation_sources: [scan]
    scan:
      type: scan
      topic: scan
      min_height: 0.0
      max_height: 2.0
      enabled: true
