<?xml version="1.0"?>
<package format="3"><name>ppe_bringup</name><version>0.1.0</version><description>PPE robot launch files.</description><maintainer email="osckar.vdo@gmail.com">Oscar I. Valenzuela</maintainer><license>Apache-2.0</license><buildtool_depend>ament_python</buildtool_depend><exec_depend>launch</exec_depend><exec_depend>launch_ros</exec_depend><exec_depend>ppe_perception</exec_depend><exec_depend>ppe_decision</exec_depend><exec_depend>ppe_alert</exec_depend><exec_depend>ppe_logger</exec_depend><exec_depend>ppe_navigation</exec_depend><export><build_type>ament_python</build_type></export></package>
